### ISSUE TITLE
프로젝트 개요를 작성한다.

### ISSUE THREAD

**Issue by sosnumber** [f-lab-edu/calorie-counter#2]
## 개요

본 프로젝트에서는 식단영양정보 서비스를 제공하는 시스템을 개발합니다. 
fatsecret 서비스는 기본적으로 사용자가 섭취한 음식을 입력하면 음식의 영양정보를 제공하는 서비스입니다.
건강한 식단관리를 할수있다는 장점이 있습니다.

서비스는 일반 이용자, 제공자, 관리자가 사용할 수 있다.
1. 일반 이용자: 일반회원이며 회원가입후 서비스를 이용할수있다.
2. 제공자: 식품에대한 세부 영양정보를 제공하는 전문가이며 서비스 관리자가 지정한다. 일반 이용자와 분리되는 별도의 가입절차를 거친다.
3. 관리자: 관리자 계정으로 전체 서비스를 관리한다.

## 기술스택

JDK 17
Spring Boot 2.7.4
MyBatis 3
MySQL 8.0 
Gradle
IntelliJ 

## 일반 사용자 기능 명세
1. 유저가 로그인한다
2. 식품 정보를 입력한다
     2-1. 식품 정보를 입력한다
          2-1-1. 아침/점심/저녁중 식품을 입력할 곳을 선택한다
          2-1-2. 식품을 검색한다 
          2-1-3. 조회된 목록에서 식품을 선택한다 
          2-1-4. 개수나 중량으로 식품을 상세입력한다
          2-1-5. 상세입력한 정보를 바탕으로 영양정보를 제공한다    
          2-1-6. 식품정보를 저장한다
     2-2. 최근에 먹은 음식으로 입력한다
          2-2-1. 최근에 자주 입력된 식품들의 목록을 보여준다 
          2-2-2. 개수나 중량으로 식품을 상세입력한다
          2-2-3. 상세입력한 정보를 바탕으로 영양정보를 제공한다   
          2-2-4. 식품정보를 저장한다
4. 식품을 입력한곳에 식품 이름,개수, 칼로리가 보여진다
     3-1. 식품정보를 조회한다
          3-1-1. 식품을 선택한다
          3-1-2. 입력했던 식품 상세정보가 보여진다
     3-2. 식품정보를 수정한다
          3-1-1. 식품을 선택한다
          3-1-2. 입력했던 식품 상세정보가 보여진다          
          3-1-3. 식품 정보를 수정한다    

## 기능스코프

사용자

- 로그인 회원가입
- 사용자 정보입력
- 식단입력,수정,삭제
- 남은 칼로리, 소비한칼로리 조회
- 내 식단목록 조회

제공자

- 식품정보입력,수정,삭제

관리자

- 회원관리

**Comment by jypthemiracle** [comment]
## 제공자 기능 명세
### USE CASE 1 - 회원가입 기능
1. 로그인 화면에서 `제공자로 가입`을 선택한다.
2. 제공자 용 회원가입 폼이 보여진다.
3. 아이디를 입력 후 중복확인 버튼을 클릭한다.
* 3-1. 존재하는 아이디가 있으면 중복 아이디 존재 메세지를 응답한다.
* 3-2. 존재하는 아이디가 없으면 사용 가능 메세지를 응답한다.
4. 비밀번호와 검증 비밀번호를 입력한다.
5. 전화번호를 입력 후 인증번호 발송 버튼을 클릭한다.
6. 유저는 3분 내에 수신한 인증번호를 입력하고 인증하기 버튼을 클릭한다.
7. 유저의 생년월일을 입력한다.
8. 영양 정보를 제공할 식단 카테고리(한식, 중식, 양식 등..) 중 하나를 선택한다.
9. 해당 분야의 전문가임을 입증할 수 있는 서류를 첨부한다.
10. 회원가입 버튼을 클릭하면 HOST 회원가입을 완료한다.
11. 로그인 화면으로 이동한다.
12. 관리자가 승인하면 제공자로서의 회원가입이 완료되었다는 이메일을 발송받는다.
13. 이메일을 클릭하여 회원가입을 확정한다.

### USE CASE 2 - 영양정보 제공 기능
1. 로그인 화면에서 `제공자 로그인` 탭을 눌러 제공자로서 로그인을 한다.
2. 식단 탭을 클릭한다.
3. 식단 탭에서 `새로운 메뉴 정보 제공하기` 버튼을 클릭한다.
4. `새로운 메뉴 정보 제공하기` 버튼을 누르면 식단 정보를 입력할 수 있는 폼이 나타난다.
5. 식단 정보를 입력할 수 있는 폼에서는 다음의 정보를 입력할 수 있다.
 * 식단 이름
 * 식단 사진 (3개 이상)
 * 식단 상세 정보
 * 식단 카테고리 (한식인지, 중식인지, 일식인지 등등)
   * 만약 기존에 존재하지 않는 카테고리라면, 새롭게 추가할 수 있다. 카테고리 추가는 별도의 다른 제공자의 허가를 필요로 하지 않는다.
 * 식단 영양정보 (Key-Value)
   * 칼로리
   * 열량 (탄수화물)
   * 단백질
   * 지방 (포화지방 및 트랜스지방 포함)
   * 당류
   * 나트륨
   * 칼슘
   * 철
   * 위에 존재하지 않는 기타 세부 영양 데이터를 추가할 수 있다. 세부 영양 데이터 추가는 별도의 다른 제공자의 허가를 필요로 하지 않는다.
6. 확인 버튼을 눌러 위의 정보를 DB에 저장한다. 이는 `등록 대기 중` 상태가 된다.
7. 다른 제공자 `등록 대기 중` 상태인 새로운 영양 정보를 확인한 후, `정보에 오류가 없음` 버튼을 각각 누를 수 있다.
8. `정보에 오류가 없음` 버튼을 클릭한 다른 제공자가 3명이 될 경우 `등록됨` 상태가 된다.
  * `등록됨` 상태가 되면 일반 사용자가 해당 식단의 영양 정보를 확인할 수 있다.
